### ISSUE TITLE
Hello! Help plizz!

### ISSUE THREAD

**Issue by timur1988** [shahwahed/packerTemplates#1]
Start deploy ubuntu 20.04
I get an answer
Build 'vsphere-iso.u2004_autoinstall' errored after 53 seconds 486 milliseconds: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

**Comment by timur1988** [comment]
![image](https://user-images.githubusercontent.com/59682661/134004668-3731eb72-a9f8-44c9-a6f5-88dd22d33cc9.png)

**Comment by shahwahed** [comment]
Hi,

Do you use windows or linux to create the image?

**Comment by timur1988** [comment]
linux !

**Comment by timur1988** [comment]
How add ssh key to host template?
Do you have an example?

**Comment by timur1988** [comment]
How create or change password root user, for provisioners "shell-local" ansible playbook install?
Plizz help!

**Comment by shahwahed** [comment]
You have to install genisoimage in order to let packer create the iso image

**Comment by shahwahed** [comment]
To add ssh key :
ssh: 
    install-server: yes
    authorized-keys: - "your SSH pub key here"
    allow-pw: no

You could add user or change in identity section.

https://tlhakhan.medium.com/ubuntu-server-20-04-autoinstall-2e5f772b655a

For detail

**Comment by timur1988** [comment]
and you did not create a virtual machine after the packer template via terraform?

**Comment by shahwahed** [comment]
I use packer to create a reference template for vsphere.

Then i use this template in terraform


But terraform doesn't use template as in vsphere. Terraform clone the template disk to create a new vm.

**Comment by timur1988** [comment]
Yes, I wrote terraform, the problem is that when cloning a template, it is not worth the included network interface

**Comment by timur1988** [comment]
```resource "vsphere_virtual_machine" "standalone" {
  name             = "${var.vm_name}"
  resource_pool_id = "${data.vsphere_host.host.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${var.vm_cpu}"
  memory   = "${var.vm_ram}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  cpu_hot_add_enabled    = true
  cpu_hot_remove_enabled = true
  memory_hot_add_enabled = true

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "${var.vm_name}.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    linked_clone  = "${var.vm_linked_clone}"

    customize {
      timeout = "20"

      linux_options {
        host_name = "${var.vm_name}"
        domain    = "${var.vm_domain}"
      }

      network_interface {
        ipv4_address = "${var.vm_ip}"
        ipv4_netmask = "${var.vm_netmask}"
      }

      ipv4_gateway    = "${var.vm_gateway}"
      dns_server_list = ["${var.vm_dns}"]
    }
  }
}

**Comment by timur1988** [comment]
@shahwahed Yes, I wrote terraform, the problem is that when cloning a template, it is not worth the included network interface

**Comment by shahwahed** [comment]
Yes is the way terraform working, it only cloning the disk of the template, you have to add either a network or copy the template one. Your syntaxe look good

**Comment by timur1988** [comment]
@shahwahed  Packer makes a template! next, through terraform, I clone the disk! there are settings in the network!Just don't check the box here:
![image](https://user-images.githubusercontent.com/59682661/134660365-12fe46ed-002d-44db-9158-2e899610ed3e.png)

**Comment by timur1988** [comment]
"vmx_data": {
        "ethernet1.startConnected": true,
      },
here is the packer configuration! but I don't know how to put these parameters in your configuration

**Comment by shahwahed** [comment]
Ok i use packer just to create the template. Then consume the template in terraform.

In my terraform settings the network is connected by default. Could be a problem when you create your template if any error occur in template could be something prevent terraform form consoming the template.

**Comment by timur1988** [comment]
I do not understand you

**Comment by shahwahed** [comment]
Hi timur1988,

I double check with ubuntu template 20.04 and 21.04.

If I use the same syntax as you in your terraform I've got the same problem as you.

I found this two relative problem : 
https://github.com/hashicorp/terraform-provider-vsphere/issues/388
and 
https://kb.vmware.com/s/article/59687

For my deployment I don't use terraform provider native command to setup IP address like you do : 

`
      customize {
            timeout = "20"
      linux_options {
        host_name = "${var.vm_name}"
        domain    = "${var.vm_domain}"
      }

      network_interface {
        ipv4_address = "${var.vm_ip}"
        ipv4_netmask = "${var.vm_netmask}"
      }

      ipv4_gateway    = "${var.vm_gateway}"
      dns_server_list = ["${var.vm_dns}"]
    }
`

But I use cloud-init, like this : 

`
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }


  extra_config = {
    "guestinfo.metadata"          = base64encode(file("../cloud-init/myVM/metadata"))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("../cloud-init/myVM/userdata"))
    "guestinfo.userdata.encoding" = "base64"
  }

`

with the following syntax : 

in metadata file : 
`
local-hostname: vmhostname
instance-id: vmhostname
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false #true to use dhcp
      addresses:
        - 192.168.1.245/24 #Set you ip here
      gateway4: 192.168.1.1 # Set gw here 
      nameservers:
        addresses:
          - 192.168.1.1 # Set DNS ip address here
# uncomment the following 3 lines to cleanup after deployement cloud-init file for security reason if you pass secret in userdata file
#cleanup-guestinfo:
#- userdata
#- vendordata

 `
and userdata file : 
`
#!/bin/sh

`

in userdata you can't either use cloud-init syntax in yaml and add your keys or other stuff, or use bash to add root command to be execute at VM first boot

I have no other solution for your problem than this one.

It is more clear now?

**Comment by timur1988** [comment]
Thanks, I already did added cloud-init cleanup and it worked.

**Comment by shahwahed** [comment]
Great
